import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

const geistSans: NextFontWithVariable = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono: NextFontWithVariable = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Latest Events",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.JSX.Element {
    return (
        <html lang="en">
            <head>
                <title>{String(metadata.title ?? "Latest Events")}</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <header className="min-h-10 bg-linear-to-r from-white to-cyan-100 to-90% sticky top-0 z-50 border-b-2 border-mist-800">
                    <div className="flex justify-around items-center">
                        <Link href="/">
                            <Image
                                src="/images/logo_black.png"
                                alt="Site logo"
                                width={50}
                                height={50}
                            />
                        </Link>
                        <nav>
                            <ul className="flex no-underline list-none gap-2.5 font-semibold text-lg">
                                <li>
                                    <Link href="/">Home</Link>
                                </li>
                                <li>
                                    <Link href="/events">Events</Link>
                                </li>
                                <li>
                                    <Link href="/about_us">About Us</Link>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <main>{children}</main>
                <footer className="bg-mist-800 text-white text-center p-4 hover:text-blue-400 hover:cursor-pointer duration-400">
                    <Link href="https://github.com/Riksev">
                        {`${new Date().getFullYear()} | Yevhenii Holubovych`}
                    </Link>
                </footer>
            </body>
        </html>
    );
}
