import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <header>
        <nav>
          <Link href="/">
            <Image src="/next.svg" alt="Site logo" width={100} height={20} />
          </Link>
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about_us">About Us</Link>
        </nav>
      </header>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
