import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Latest Events",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>{metadata.title}</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <header className="min-h-10 bg-linear-to-r from-white to-cyan-100 to-90%">
                    <div className="flex justify-around items-center">
                        <Link href="/">
                            <Image
                                src="/images/logo_black.png"
                                alt="Site logo"
                                width={50}
                                height={50}
                            />
                        </Link>
                        <nav>
                            <ul className="flex no-underline list-none gap-2.5 font-semibold text-lg">
                                <li>
                                    <Link href="/">Home</Link>
                                </li>
                                <li>
                                    <Link href="/events">Events</Link>
                                </li>
                                <li>
                                    <Link href="/about_us">About Us</Link>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <main>{children}</main>
                <footer className="bg-mist-800 text-white text-center p-4 hover:text-blue-400 hover:cursor-pointer duration-400">
                    <p>{`${new Date().getFullYear()} | Yevhenii Holubovych`}</p>
                    <p>based on CodeCamp course</p>
                </footer>
            </body>
        </html>
    );
}
