import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Latest Events",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav>
            <Link href="/">
              <Image
                src="/next.svg"
                alt="Site logo"
                width={100}
                height={20}
                style={{filter: "invert(100%)"}}
              />
            </Link>
            <Link href="/">Home</Link>
            <Link href="/events">Events</Link>
            <Link href="/about_us">About Us</Link>
          </nav>
        </header>
        <div className={styles.page}>
          <main>{children}</main>
        </div>
        <footer className={styles.footer}>
          <p>{`${new Date().getFullYear()} | Yevhenii Holubovych`}</p>
          <p>based on CodeCamp course</p>
        </footer>
      </body>
    </html>
  );
}
